### ISSUE TITLE
Failure on `make serve`: Unknown tag 'link'

### ISSUE THREAD

**Issue by naught101** [swcarpentry/lesson-example#143] opened 2017-11-10 04:38 UTC
When trying to get Jekyll to serve these pages for testing, I hit the following problem:

```
(science) zoro➜  lesson-example git:(gh-pages) ✗ $ make serve 
jekyll serve
Configuration file: /data/documents/science/software_carpentry/lesson-example/_config.yml
            Source: /data/documents/science/software_carpentry/lesson-example
       Destination: /data/documents/science/software_carpentry/lesson-example/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 30): Unknown tag 'link' in _includes/navbar.html, included in _layouts/base.html
jekyll 3.1.6 | Error:  Liquid syntax error (line 30): Unknown tag 'link'
Makefile:21: recipe for target 'serve' failed
make: *** [serve] Error 1
```

Any ideas what might cause this, and how I can get Jekyll to run?

**Comment by rgaiacs** [comment] 2017-11-11 10:57
@naught101 Thanks for the issue.

Please update your Jekyll installation to 3.2 or higher. `link` was introduced in 3.2.0, see [the release note](https://jekyllrb.com/news/2016/07/26/jekyll-3-2-0-released/). From August 23, 2016 GitHub Pages uses Jekyll 3.2, see [this blog post](https://github.com/blog/2236-github-pages-now-runs-jekyll-3-2), so `link` is available to use in our current workflow.

I'm closing this as not a bug. Thanks for the report again.

**Closed by rgaiacs** 2017-11-11 10:57 UTC
