### ISSUE TITLE
`make serve` broken

### ISSUE THREAD

**Issue by psteinb** [swcarpentry/lesson-example#155] opened 2017-11-27 10:13 UTC
I just wanted to merge the lesson-{template,styles} 9.3.1 into `hpc-novice`, but encountered an error while asking jekyll to serve the page. the same error appears in this repo:

```
$ make serve
jekyll serve
Configuration file: /scratch/steinbac/development/softwarecarpentry/public/lesson-example/_config.yml
            Source: /scratch/steinbac/development/softwarecarpentry/public/lesson-example
       Destination: /scratch/steinbac/development/softwarecarpentry/public/lesson-example/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Could not find document 'index.md' in tag 'link'. Make sure the document exists and the path is correct. in /_layouts/base.html
jekyll 3.2.1 | Error:  Could not find document 'index.md' in tag 'link'.

Make sure the document exists and the path is correct.

make: *** [Makefile:21: serve] Error 1
```

**Comment by rgaiacs** [comment] 2017-11-27 10:34
Hi @psteinb  Thanks for the issue.

Please update your Jekyll installation to 3.2 or higher. `link` was introduced in 3.2.0, see [the release note](https://jekyllrb.com/news/2016/07/26/jekyll-3-2-0-released/). From August 23, 2016 GitHub Pages uses Jekyll 3.2, see [this blog post](https://github.com/blog/2236-github-pages-now-runs-jekyll-3-2), so link is available to use in our current workflow.

I'm closing this as not a bug and as duplicated of #143. Thanks for the report again.

**Closed by rgaiacs** 2017-11-27 10:34 UTC

**Comment by psteinb** [comment] 2017-11-27 10:48
ok, `gem install jekyll` did bring my jekyll to 2017 apparently. ;) 
thanks for the hint.
