### ISSUE TITLE
Liquid Exception: Liquid syntax error: 

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/lesson-example#152] opened 2017-11-21 14:21 UTC
I followed the merge instructions for lesson style v9.3.0, and got this error message when trying to build the site locally.

```
$ make serve
Liquid Exception: Liquid syntax error: Unknown tag 'link' in _includes/navbar.html, included in _layouts/base.html
jekyll 3.0.1 | Error:  Liquid syntax error: Unknown tag 'link'
Makefile:21: recipe for target 'serve' failed
make: *** [serve] Error 1

```

**Comment by rgaiacs** [comment] 2017-11-21 14:45
Please update your Jekyll installation to 3.2 or higher. link was introduced in 3.2.0, see [the release note](https://jekyllrb.com/news/2016/07/26/jekyll-3-2-0-released/). From August 23, 2016 GitHub Pages uses Jekyll 3.2, see [this blog post](https://github.com/blog/2236-github-pages-now-runs-jekyll-3-2), so link is available to use in our current workflow.

Close as duplicate of #143.

**Closed by rgaiacs** 2017-11-21 14:45 UTC
