### ISSUE TITLE
svg images not displayed

### ISSUE THREAD

**Issue by baender** [swcarpentry/lesson-example#171] opened 2018-02-09 19:52 UTC
svg images are not displayed on
https://swcarpentry.github.io/lesson-example/02-tooling/index.html
and also other episodes

**Comment by ErinBecker** [comment] 2018-02-09 21:07
The images display for me: 

![screen shot 2018-02-09 at 1 06 41 pm](https://user-images.githubusercontent.com/19176319/36050133-1be966da-0d9a-11e8-8c63-0b611b23aa5a.png)

@baender - could you please add a screenshot of what you see?

**Comment by twitwi** [comment] 2018-02-10 10:20
I can reproduce it (nothing displayed) with firefox. After looking at the SVG, having a good idea of what could go wrong, it seems that `clip-path="url(#presentation_clip_path)" ` is causing the issue.

A quick workaround would be to remove the clip-path from the root svg element.

**Comment by baender** [comment] 2018-02-10 12:25
I am also using Firefox (58.0.2 64-Bit). Screenshot is attached. Space is reserved in the page but is blank. "View Image" results in a pure blank site.

![swc_lesson_example_no_svg](https://user-images.githubusercontent.com/9801139/36062070-3adc7b60-0e65-11e8-8108-fed04fc10952.png)

**Comment by twitwi** [comment] 2018-02-10 17:28
I'll be making a simpler example and opening a bug report on firefox.

Still, the workaround needs to be implemented in the meantime, and we might tag this as "newcomer-friendly". Here is some guidance:
- install firefox to reproduce the problem
- manage to open the svg files using a text editor (not a visual SVG editor) and remove the clip-path="..." on the first line
- check that it displays with firefox and at least another browser,
- make a pull request

**Comment by twitwi** [comment] 2018-02-11 18:36
https://bugzilla.mozilla.org/show_bug.cgi?id=1437389

**Comment by ErinBecker** [comment] 2018-02-11 20:58
@fmichonneau - I remember you saying that this issue is related to use of http vs https.

**Comment by fmichonneau** [comment] 2018-02-11 21:10
it doesn't seem related to the mixing of http and https in this particular case. It seems that @twitwi is correct. I don't know enough about the SVG specs to tell. Is it worth editing the SVG files to remove the `clip-path` element, or is the file valid it's a bug with Firefox and we need another workaround until it's fixed there?

**Comment by twitwi** [comment] 2018-02-11 21:47
I'd recommend implementing the workaround (removing the clip-path, whicih is automatically generated and not necessary in this case).

I now think it is a firefox bug. Although SVG support has always been of very good in firefox, it is a very specific corner case and it might take some time to be tracked down and fixed.

**Comment by rgaiacs** [comment] 2018-02-12 11:25
@twitwi Thanks very much for digging this report. And for the report to Firefox.

Most of the diagrams are created in LibreOffice Draw. The motivation is that LibreOffice is available in Windows, macOS and Linux. Also LibreOffice Draw is more novice user friendly than Inkscape, also available for Windows macOS and Linux.

This report need to be report upstream to LibreOffice. I have a quick look and someone reported https://bugs.documentfoundation.org/show_bug.cgi?id=108529. When investigating this issue, I encounter https://bugs.documentfoundation.org/show_bug.cgi?id=115648. I couldn't discover which part of our LibreOffice Draw file is breaking the SVG.

# Instructions for Novice

1. Open `fig/forking.odg` with LibreOffice.
2. Remove all the elements except for one.
3. Export the file as SVG. From the top bar, File -> Export -> SVG.
4. Test the file with Firefox.
5. If you can only see a white canvas in Firefox, leave a comment and attach the LibreOffice Draw file here.
6. (If you want to report upstream). Go to https://bugs.documentfoundation.org/ and open a issue. **Include the link to the issue here.**

**Comment by fmichonneau** [comment] 2018-02-12 20:08
I updated the SVG files in this repo so they render correctly. I'm going to search through the other repos to see if other images are affected by this bug.

**Comment by fmichonneau** [comment] 2018-02-12 20:39
interestingly, it looks like the images in the python lesson include the `clip-path` element but still display in Firefox: http://swcarpentry.github.io/python-novice-inflammation/01-numpy/

**Comment by twitwi** [comment] 2018-02-12 20:39
New buzilla ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1437660

**Comment by rgaiacs** [comment] 2018-02-13 11:01
[diff-libreoffice-5-4.diff.txt](https://github.com/swcarpentry/lesson-example/files/1719604/diff-libreoffice-5-4.diff.txt)
@twitwi Thanks for the ticket.

@fmichonneau Thanks for the commit. Please don't close a issue when we are still having a discussion of how to fix the problem in a way that it will not hunt us down later on.

~~~
$ git log -1
commit faa28db869dca19b3c59f060cfa42eba85711ae9 (HEAD, swc/gh-pages)
Merge: 3fd1434 fc317bb
Author: François Michonneau <francois.michonneau@gmail.com>
Date:   Mon Feb 12 12:07:05 2018 -0800

    Merge pull request #173 from fmichonneau/fix-svg
    
    [fix #171] remove "clip-path" attribute
$ libreoffice --version               
LibreOffice 5.4.4.2 40m0(Build:2)
$ libreoffice --convert-to svg --outdir fig fig/forking.odg 
convert /home/raniere/software-carpentry/swc-lesson-example/fig/forking.odg -> /home/raniere/software-carpentry/swc-lesson-example/fig/forking.svg using filter : draw_svg_Export
Overwriting: /home/raniere/software-carpentry/swc-lesson-example/fig/forking.svg
$ git diff > diff-libreoffice-5-4.diff.txt
~~~

[diff-libreoffice-5-4.diff.txt](https://github.com/swcarpentry/lesson-example/files/1719607/diff-libreoffice-5-4.diff.txt) is not empty!

And the new SVG file is corrupt, see the screenshot below.

![screenshot from 2018-02-13 11-00-04](https://user-images.githubusercontent.com/1506457/36146592-145f261e-10ad-11e8-81e2-c0553f0ea8ad.png)

**Comment by rgaiacs** [comment] 2018-02-13 17:09
> Is the screenshot you are attaching based on the file you got from the repository or the one you regenerated from the odg file? If the latter, it might be affected by a different bug.

Is the one regenerated from the `.odg` file. Sorry for not be very clear. The one in the repository looks fine.

I will keep the conversation in https://github.com/swcarpentry/styles/pull/203 because this is not restrict to this repository. Please keep it open until we resolve https://github.com/swcarpentry/styles/pull/203. Thanks.

**Comment by twitwi** [comment] 2018-02-15 19:46
The bug has been confirmed: https://bugzilla.mozilla.org/show_bug.cgi?id=1437660

**Comment by rgaiacs** [comment] 2018-02-20 10:26
@baender Thanks for the report. 

@twitwi et al. Thanks for the contributions. I'm closing this issue based on https://github.com/swcarpentry/lesson-example/pull/179. LibreOffice 6.0.1 is generating a good SVG for Chrome and Firefox. This looks good to me in terms of reproducible build.

**Closed by rgaiacs** 2018-02-20 10:26 UTC
